package debug

import (
	"bytes"
	_ "embed"
	"fmt"
	"strings"
	"text/template"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
)

var (
	// Address of the debug contract.
	addr = common.HexToAddress("0x000000000000000000000000000000000baDC0DE")

	// Source of the debug contract.
	Src string

	funcs = map[[4]byte]abi.Arguments{}
	args  = [][]string{
		{"uint256"},
		{"string"},
		{"bool"},
		{"address"},
		{"uint256", "uint256"},
		{"uint256", "string"},
		{"uint256", "bool"},
		{"uint256", "address"},
		{"string", "uint256"},
		{"string", "string"},
		{"string", "bool"},
		{"string", "address"},
		{"bool", "uint256"},
		{"bool", "string"},
		{"bool", "bool"},
		{"bool", "address"},
		{"address", "uint256"},
		{"address", "string"},
		{"address", "bool"},
		{"address", "address"},
		{"uint256", "uint256", "uint256"},
		{"uint256", "uint256", "string"},
		{"uint256", "uint256", "bool"},
		{"uint256", "uint256", "address"},
		{"uint256", "string", "uint256"},
		{"uint256", "string", "string"},
		{"uint256", "string", "bool"},
		{"uint256", "string", "address"},
		{"uint256", "bool", "uint256"},
		{"uint256", "bool", "string"},
		{"uint256", "bool", "bool"},
		{"uint256", "bool", "address"},
		{"uint256", "address", "uint256"},
		{"uint256", "address", "string"},
		{"uint256", "address", "bool"},
		{"uint256", "address", "address"},
		{"string", "uint256", "uint256"},
		{"string", "uint256", "string"},
		{"string", "uint256", "bool"},
		{"string", "uint256", "address"},
		{"string", "string", "uint256"},
		{"string", "string", "string"},
		{"string", "string", "bool"},
		{"string", "string", "address"},
		{"string", "bool", "uint256"},
		{"string", "bool", "string"},
		{"string", "bool", "bool"},
		{"string", "bool", "address"},
		{"string", "address", "uint256"},
		{"string", "address", "string"},
		{"string", "address", "bool"},
		{"string", "address", "address"},
		{"bool", "uint256", "uint256"},
		{"bool", "uint256", "string"},
		{"bool", "uint256", "bool"},
		{"bool", "uint256", "address"},
		{"bool", "string", "uint256"},
		{"bool", "string", "string"},
		{"bool", "string", "bool"},
		{"bool", "string", "address"},
		{"bool", "bool", "uint256"},
		{"bool", "bool", "string"},
		{"bool", "bool", "bool"},
		{"bool", "bool", "address"},
		{"bool", "address", "uint256"},
		{"bool", "address", "string"},
		{"bool", "address", "bool"},
		{"bool", "address", "address"},
		{"address", "uint256", "uint256"},
		{"address", "uint256", "string"},
		{"address", "uint256", "bool"},
		{"address", "uint256", "address"},
		{"address", "string", "uint256"},
		{"address", "string", "string"},
		{"address", "string", "bool"},
		{"address", "string", "address"},
		{"address", "bool", "uint256"},
		{"address", "bool", "string"},
		{"address", "bool", "bool"},
		{"address", "bool", "address"},
		{"address", "address", "uint256"},
		{"address", "address", "string"},
		{"address", "address", "bool"},
		{"address", "address", "address"},
		{"uint256", "uint256", "uint256", "uint256"},
		{"uint256", "uint256", "uint256", "string"},
		{"uint256", "uint256", "uint256", "bool"},
		{"uint256", "uint256", "uint256", "address"},
		{"uint256", "uint256", "string", "uint256"},
		{"uint256", "uint256", "string", "string"},
		{"uint256", "uint256", "string", "bool"},
		{"uint256", "uint256", "string", "address"},
		{"uint256", "uint256", "bool", "uint256"},
		{"uint256", "uint256", "bool", "string"},
		{"uint256", "uint256", "bool", "bool"},
		{"uint256", "uint256", "bool", "address"},
		{"uint256", "uint256", "address", "uint256"},
		{"uint256", "uint256", "address", "string"},
		{"uint256", "uint256", "address", "bool"},
		{"uint256", "uint256", "address", "address"},
		{"uint256", "string", "uint256", "uint256"},
		{"uint256", "string", "uint256", "string"},
		{"uint256", "string", "uint256", "bool"},
		{"uint256", "string", "uint256", "address"},
		{"uint256", "string", "string", "uint256"},
		{"uint256", "string", "string", "string"},
		{"uint256", "string", "string", "bool"},
		{"uint256", "string", "string", "address"},
		{"uint256", "string", "bool", "uint256"},
		{"uint256", "string", "bool", "string"},
		{"uint256", "string", "bool", "bool"},
		{"uint256", "string", "bool", "address"},
		{"uint256", "string", "address", "uint256"},
		{"uint256", "string", "address", "string"},
		{"uint256", "string", "address", "bool"},
		{"uint256", "string", "address", "address"},
		{"uint256", "bool", "uint256", "uint256"},
		{"uint256", "bool", "uint256", "string"},
		{"uint256", "bool", "uint256", "bool"},
		{"uint256", "bool", "uint256", "address"},
		{"uint256", "bool", "string", "uint256"},
		{"uint256", "bool", "string", "string"},
		{"uint256", "bool", "string", "bool"},
		{"uint256", "bool", "string", "address"},
		{"uint256", "bool", "bool", "uint256"},
		{"uint256", "bool", "bool", "string"},
		{"uint256", "bool", "bool", "bool"},
		{"uint256", "bool", "bool", "address"},
		{"uint256", "bool", "address", "uint256"},
		{"uint256", "bool", "address", "string"},
		{"uint256", "bool", "address", "bool"},
		{"uint256", "bool", "address", "address"},
		{"uint256", "address", "uint256", "uint256"},
		{"uint256", "address", "uint256", "string"},
		{"uint256", "address", "uint256", "bool"},
		{"uint256", "address", "uint256", "address"},
		{"uint256", "address", "string", "uint256"},
		{"uint256", "address", "string", "string"},
		{"uint256", "address", "string", "bool"},
		{"uint256", "address", "string", "address"},
		{"uint256", "address", "bool", "uint256"},
		{"uint256", "address", "bool", "string"},
		{"uint256", "address", "bool", "bool"},
		{"uint256", "address", "bool", "address"},
		{"uint256", "address", "address", "uint256"},
		{"uint256", "address", "address", "string"},
		{"uint256", "address", "address", "bool"},
		{"uint256", "address", "address", "address"},
		{"string", "uint256", "uint256", "uint256"},
		{"string", "uint256", "uint256", "string"},
		{"string", "uint256", "uint256", "bool"},
		{"string", "uint256", "uint256", "address"},
		{"string", "uint256", "string", "uint256"},
		{"string", "uint256", "string", "string"},
		{"string", "uint256", "string", "bool"},
		{"string", "uint256", "string", "address"},
		{"string", "uint256", "bool", "uint256"},
		{"string", "uint256", "bool", "string"},
		{"string", "uint256", "bool", "bool"},
		{"string", "uint256", "bool", "address"},
		{"string", "uint256", "address", "uint256"},
		{"string", "uint256", "address", "string"},
		{"string", "uint256", "address", "bool"},
		{"string", "uint256", "address", "address"},
		{"string", "string", "uint256", "uint256"},
		{"string", "string", "uint256", "string"},
		{"string", "string", "uint256", "bool"},
		{"string", "string", "uint256", "address"},
		{"string", "string", "string", "uint256"},
		{"string", "string", "string", "string"},
		{"string", "string", "string", "bool"},
		{"string", "string", "string", "address"},
		{"string", "string", "bool", "uint256"},
		{"string", "string", "bool", "string"},
		{"string", "string", "bool", "bool"},
		{"string", "string", "bool", "address"},
		{"string", "string", "address", "uint256"},
		{"string", "string", "address", "string"},
		{"string", "string", "address", "bool"},
		{"string", "string", "address", "address"},
		{"string", "bool", "uint256", "uint256"},
		{"string", "bool", "uint256", "string"},
		{"string", "bool", "uint256", "bool"},
		{"string", "bool", "uint256", "address"},
		{"string", "bool", "string", "uint256"},
		{"string", "bool", "string", "string"},
		{"string", "bool", "string", "bool"},
		{"string", "bool", "string", "address"},
		{"string", "bool", "bool", "uint256"},
		{"string", "bool", "bool", "string"},
		{"string", "bool", "bool", "bool"},
		{"string", "bool", "bool", "address"},
		{"string", "bool", "address", "uint256"},
		{"string", "bool", "address", "string"},
		{"string", "bool", "address", "bool"},
		{"string", "bool", "address", "address"},
		{"string", "address", "uint256", "uint256"},
		{"string", "address", "uint256", "string"},
		{"string", "address", "uint256", "bool"},
		{"string", "address", "uint256", "address"},
		{"string", "address", "string", "uint256"},
		{"string", "address", "string", "string"},
		{"string", "address", "string", "bool"},
		{"string", "address", "string", "address"},
		{"string", "address", "bool", "uint256"},
		{"string", "address", "bool", "string"},
		{"string", "address", "bool", "bool"},
		{"string", "address", "bool", "address"},
		{"string", "address", "address", "uint256"},
		{"string", "address", "address", "string"},
		{"string", "address", "address", "bool"},
		{"string", "address", "address", "address"},
		{"bool", "uint256", "uint256", "uint256"},
		{"bool", "uint256", "uint256", "string"},
		{"bool", "uint256", "uint256", "bool"},
		{"bool", "uint256", "uint256", "address"},
		{"bool", "uint256", "string", "uint256"},
		{"bool", "uint256", "string", "string"},
		{"bool", "uint256", "string", "bool"},
		{"bool", "uint256", "string", "address"},
		{"bool", "uint256", "bool", "uint256"},
		{"bool", "uint256", "bool", "string"},
		{"bool", "uint256", "bool", "bool"},
		{"bool", "uint256", "bool", "address"},
		{"bool", "uint256", "address", "uint256"},
		{"bool", "uint256", "address", "string"},
		{"bool", "uint256", "address", "bool"},
		{"bool", "uint256", "address", "address"},
		{"bool", "string", "uint256", "uint256"},
		{"bool", "string", "uint256", "string"},
		{"bool", "string", "uint256", "bool"},
		{"bool", "string", "uint256", "address"},
		{"bool", "string", "string", "uint256"},
		{"bool", "string", "string", "string"},
		{"bool", "string", "string", "bool"},
		{"bool", "string", "string", "address"},
		{"bool", "string", "bool", "uint256"},
		{"bool", "string", "bool", "string"},
		{"bool", "string", "bool", "bool"},
		{"bool", "string", "bool", "address"},
		{"bool", "string", "address", "uint256"},
		{"bool", "string", "address", "string"},
		{"bool", "string", "address", "bool"},
		{"bool", "string", "address", "address"},
		{"bool", "bool", "uint256", "uint256"},
		{"bool", "bool", "uint256", "string"},
		{"bool", "bool", "uint256", "bool"},
		{"bool", "bool", "uint256", "address"},
		{"bool", "bool", "string", "uint256"},
		{"bool", "bool", "string", "string"},
		{"bool", "bool", "string", "bool"},
		{"bool", "bool", "string", "address"},
		{"bool", "bool", "bool", "uint256"},
		{"bool", "bool", "bool", "string"},
		{"bool", "bool", "bool", "bool"},
		{"bool", "bool", "bool", "address"},
		{"bool", "bool", "address", "uint256"},
		{"bool", "bool", "address", "string"},
		{"bool", "bool", "address", "bool"},
		{"bool", "bool", "address", "address"},
		{"bool", "address", "uint256", "uint256"},
		{"bool", "address", "uint256", "string"},
		{"bool", "address", "uint256", "bool"},
		{"bool", "address", "uint256", "address"},
		{"bool", "address", "string", "uint256"},
		{"bool", "address", "string", "string"},
		{"bool", "address", "string", "bool"},
		{"bool", "address", "string", "address"},
		{"bool", "address", "bool", "uint256"},
		{"bool", "address", "bool", "string"},
		{"bool", "address", "bool", "bool"},
		{"bool", "address", "bool", "address"},
		{"bool", "address", "address", "uint256"},
		{"bool", "address", "address", "string"},
		{"bool", "address", "address", "bool"},
		{"bool", "address", "address", "address"},
		{"address", "uint256", "uint256", "uint256"},
		{"address", "uint256", "uint256", "string"},
		{"address", "uint256", "uint256", "bool"},
		{"address", "uint256", "uint256", "address"},
		{"address", "uint256", "string", "uint256"},
		{"address", "uint256", "string", "string"},
		{"address", "uint256", "string", "bool"},
		{"address", "uint256", "string", "address"},
		{"address", "uint256", "bool", "uint256"},
		{"address", "uint256", "bool", "string"},
		{"address", "uint256", "bool", "bool"},
		{"address", "uint256", "bool", "address"},
		{"address", "uint256", "address", "uint256"},
		{"address", "uint256", "address", "string"},
		{"address", "uint256", "address", "bool"},
		{"address", "uint256", "address", "address"},
		{"address", "string", "uint256", "uint256"},
		{"address", "string", "uint256", "string"},
		{"address", "string", "uint256", "bool"},
		{"address", "string", "uint256", "address"},
		{"address", "string", "string", "uint256"},
		{"address", "string", "string", "string"},
		{"address", "string", "string", "bool"},
		{"address", "string", "string", "address"},
		{"address", "string", "bool", "uint256"},
		{"address", "string", "bool", "string"},
		{"address", "string", "bool", "bool"},
		{"address", "string", "bool", "address"},
		{"address", "string", "address", "uint256"},
		{"address", "string", "address", "string"},
		{"address", "string", "address", "bool"},
		{"address", "string", "address", "address"},
		{"address", "bool", "uint256", "uint256"},
		{"address", "bool", "uint256", "string"},
		{"address", "bool", "uint256", "bool"},
		{"address", "bool", "uint256", "address"},
		{"address", "bool", "string", "uint256"},
		{"address", "bool", "string", "string"},
		{"address", "bool", "string", "bool"},
		{"address", "bool", "string", "address"},
		{"address", "bool", "bool", "uint256"},
		{"address", "bool", "bool", "string"},
		{"address", "bool", "bool", "bool"},
		{"address", "bool", "bool", "address"},
		{"address", "bool", "address", "uint256"},
		{"address", "bool", "address", "string"},
		{"address", "bool", "address", "bool"},
		{"address", "bool", "address", "address"},
		{"address", "address", "uint256", "uint256"},
		{"address", "address", "uint256", "string"},
		{"address", "address", "uint256", "bool"},
		{"address", "address", "uint256", "address"},
		{"address", "address", "string", "uint256"},
		{"address", "address", "string", "string"},
		{"address", "address", "string", "bool"},
		{"address", "address", "string", "address"},
		{"address", "address", "bool", "uint256"},
		{"address", "address", "bool", "string"},
		{"address", "address", "bool", "bool"},
		{"address", "address", "bool", "address"},
		{"address", "address", "address", "uint256"},
		{"address", "address", "address", "string"},
		{"address", "address", "address", "bool"},
		{"address", "address", "address", "address"},
	}

	//go:embed debug.template.sol
	debugTmplSrc string
	debugTmpl    = template.Must(
		template.New("debug.sol").
			Funcs(template.FuncMap{
				"typeToArg": typeToArg,
			}).
			Parse(debugTmplSrc),
	)
)

func init() {
	// generate debug.sol from template
	buf := bytes.NewBuffer(nil)
	if err := debugTmpl.Execute(buf, &model{
		Addr:       addr,
		Signatures: args,
	}); err != nil {
		panic(fmt.Sprintf("debug: %v", err))
	}
	Src = buf.String()

	// generate funcs
	for _, a := range args {
		sig := "log(" + strings.Join(a, ",") + ")"
		sel := *(*[4]byte)(crypto.Keccak256([]byte(sig))[:4])

		abiArgs := make(abi.Arguments, len(a))
		for i, arg := range a {
			typ, err := abi.NewType(arg, "", nil)
			if err != nil {
				panic(fmt.Sprintf("debug: %v", err))
			}
			abiArgs[i] = abi.Argument{Type: typ}
		}
		funcs[sel] = abiArgs
	}
}

type model struct {
	Addr       common.Address
	Signatures [][]string
}

func typeToArg(t string) string {
	switch t {
	case "bytes":
		return "bytes memory"
	case "string":
		return "string memory"
	default:
		return t
	}
}
