// Code generated by go generate; DO NOT EDIT.
// SPDX-License-Identifier: MIT
pragma solidity >=0.5.0 <0.9.0;

import "console.sol";

contract ConsoleTest {

    function testHello() external pure {
        console.log("Hello, World!");
    }

    function testInt() external pure {
        console.logInt(-42);
    }

    function testBytes() external pure {
        console.logBytes(abi.encodePacked("test"));
    }

    function testBytes1() external pure {
        console.logBytes1(0xff);
    }

    function testAddress() external pure {
        console.logAddress(address(0xc0fe));
    }

    function testBool() external pure {
        console.logBool(true);
    }
}
